name:                bot
version:             0.1.0.0
github:              "vanadiiii/bot"
license:             BSD3
author:              "Ivan Matveev"
maintainer:          "vanadiiii42@gmail.com"
copyright:           "Copyright (c) Ivan Matveev"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/vanadiiii/bot#readme>

dependencies:
- base >= 4.7 && < 5
- telegram-api >= 0.7
- http-client >= 0.5
- http-client-tls >= 0.3

library:
  source-dirs: src

executables:
  bot-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bot

tests:
  bot-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bot
